# Generated by Django 3.1.7 on 2021-03-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_scripts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=50)),
                ('script_author', models.CharField(max_length=30)),
                ('script_file', models.FileField(upload_to='media')),
                ('description', models.CharField(max_length=2000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Scripts',
        ),
    ]
